version: '3.8'

services:
  app:
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}  
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}  
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
    ports:
      - "3060:3060"
    command: ["npm", "start"]
